language: c
cache: ccache
sudo: true
dist: trusty

services:
  - docker

before_install:
  -  docker pull librecores/librecores-ci-openrisc
  -  docker images

script:
- docker run --rm -v $(pwd):/src -e "JOB=$JOB" -e "SIM=$SIM" -e "EXPECTED_FAILURES=$EXPECTED_FAILURES" librecores/librecores-ci-openrisc /src/.travis/test.sh

matrix:
  fast_finish: true

jobs:
  include:
    - stage: verilator
      env: JOB=verilator
    - stage: testing
      env: JOB=or1k-tests SIM=icarus EXPECTED_FAILURES="or1k-cy or1k-ov or1k-shortjump"

